name: Run Tests API
on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and run Docker containers
        run: docker-compose up -d --build

  unit_tests:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: docker-compose exec web python manage.py test users.tests.unitTests

  functional_tests:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Robot Functional Tests
        run: docker-compose exec web robot users/tests/functionalTests/

  contract_tests:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run contract tests
        run: docker-compose exec web python manage.py users/tests/contractTests/

  performance_tests:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run performance test
        run: docker-compose exec web python manage.py test users.tests.performanceTests

  security_tests:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Robot Security Tests
        run: docker-compose exec web robot users/tests/securityTests/

  shutdown:
    runs-on: ubuntu-latest
    needs:
      - unit_tests
      - functional_tests
      - contract_tests
      - performance_tests
      - security_tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Shut down Docker containers
        run: docker-compose down
