name: Run Tests API
on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

  unit_tests:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Run unit tests
        run: python manage.py test users.tests.unitTests

  functional_tests:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Run Robot Functional Tests
        run: robot users/tests/functionalTests/

  contract_tests:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Run contract tests
        run: python manage.py users/tests/contractTests/

  performance_tests:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Run performance test
        run: python manage.py test users.tests.performanceTests

  security_tests:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Run Robot Security Tests
        run: robot users/tests/securityTests/
